#!/bin/sh
# sourced at boot by ~/.xinitrc and most display managers


# Include ~/.local/bin into PATH
export PATH="$HOME/.local/bin:$PATH"

#nm-applet &
#volumeicon &
#xfce4-power-manager &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#gnome-keyring-daemon --start --components=pkcs11 &
# xset dpms 600 900 1200
# xset r rate 350 60

# Set defaults
export VISUAL="nvim"
export EDITOR="nvim"
export BROWSER="firefox"
export QT_QPA_PLATFORMTHEME="qt5ct"
export TERM="xterm-kitty"
export XDG_CONFIG_HOME="$HOME/.config"

# Set Java Environment
archlinux-java set java-15-openjdk
export _JAVA_AWT_WM_NONREPARENTING=1
