#!/bin/sh
# sourced at boot by ~/.xinitrc and most display managers


# Include ~/.local/bin into PATH
export PATH="$HOME/.local/bin:$PATH"

#nm-applet &
#volumeicon &
#xfce4-power-manager &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#gnome-keyring-daemon --start --components=pkcs11 &
# xset dpms 600 900 1200
# xset r rate 350 60

# Set defaults
export VISUAL="nvim"
export EDITOR="nvim"
export BROWSER="firefox"

export MANPATH="/usr/share/man"
export MANPAGER="sh -c 'col -bx | bat -l man -p --paging always'"

export QT_QPA_PLATFORMTHEME="qt5ct"

export TERM="xterm-kitty"

export XDG_CONFIG_HOME="$HOME/.config"
# Go
export PATH="$PATH:$HOME/go/bin"
export GOPATH=$HOME/go

# Set Java Environment
archlinux-java set java-15-openjdk
export _JAVA_AWT_WM_NONREPARENTING=1
# Qt
export QT_SELECT=5
export QT_AUTO_SCREEN_SCALE_FACTOR=1
# Nvidia Prime Offloading 
# https://github.com/Askannz/optimus-manager/wiki/Nvidia-GPU-offloading-for-%22hybrid%22-mode
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME="nvidia"
__VK_LAYER_NV_optimus="NVIDIA_only"

# fzf
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS="--preview 'pistol {}' --layout=reverse --inline-info --height 100% --border --margin=1 --padding=1 --color=bg+:#3B4252,bg:#2E3440,spinner:#81A1C1,hl:#616E88,fg:#D8DEE9,header:#616E88,info:#81A1C1,pointer:#81A1C1,marker:#81A1C1,fg+:#D8DEE9,prompt:#81A1C1,hl+:#81A1C1"

# autorun
git-auto -d /home/bdr/git/logseq-2nd-brain -b main -i 300 -p &
