icons_format = "{icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "awesome5"
[icons.overrides]
update = "" 

#[[block]]
#block = "net"
#device = "enp0s31f6"
#interval = 5
[[block]]
block = "uptime"
interval = 3600 # update every hour


[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "sound"
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "pavucontrol"
[icon.overrides]

[[block]]
block = "privacy"
[[block.driver]]
name = "v4l"
[[block.driver]]
name = "pipewire"
exclude_input = ["openrgb"]
display = "nickname"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "



