#!/usr/bin/env bash

# Depends: Mugshot


awesome_dir="${HOME}/.config/awesome/"
user_profile_dir="${awesome_dir}/config/user-profile/"

accountsservice_user_icons="/var/lib/AccountsService/icons/${USER}"

# Check if user image exists
if [ -f "${user_profile_dir}${USER}.png" ];
then
    if [ -f "${accountsservice_user_icons}" ];
    then
        if ! cmp --silent "${user_profile_dir}${USER}.png" "${accountsservice_user_icons}";
        then
            cp "${accountsservice_user_icons}" "${user_profile_dir}${USER}.png"
        fi
        printf "%s%s.png" "${user_profile_dir}" "${USER}"
    else
        printf "%s%s.png" "${user_profile_dir}" "${USER}"

    fi
    exit;
else
    if [ -f "${accountsservice_user_icons}" ];
    then
        cp "${accountsservice_user_icons}" "${user_profile_dir}${USER}.png"
        printf "%s%s.png" "${user_profile_dir}" "${USER}"
        exit;
    else
        printf "default"
        exit;
    fi
fi